algoritmo "Quiz"
// Função :
// Autor :
// Data : 11/8/2012
// Seção de Declarações 
var
resposta : caracter
inicio
escreval ("Em qual Estado se localiza Brasília?")
escreval ("A) Bahia")
escreval ("B) Minas Gerais")
escreval ("C) Distrito Federal")
escreval ("D) São Paulo")
escreval ("E) Mato Grosso")
leia (resposta)
se (resposta = "C")entao
   escreva ("Resposta correta!")
senao
   escreva ("Resposta incorreta!")
fimse
// Seção de Comandos 
fimalgoritmo
