algoritmo "operadores"
// Função :
// Autor :
// Data : 11/8/2012
// Seção de Declarações 
var
resultado1, resultado2 : real
resultado3 : logico
texto : caracter
inicio
texto <- "Exemplos de Operadores"
Escreval (maiusc (texto))
resultado1 <- 9 mod 2
resultado2 <- 8^2 + 10 * 2
resultado3 <- 15 <> 2
Escreval ("9 mod 2 =", resultado1)
Escreval ("8^2 + 10 * 2 =", resultado2)
Escreval ("15 <> 2 =", resultado3)
// Seção de Comandos 
fimalgoritmo
